### ISSUE TITLE
unicode characters do not seem to be handled

### ISSUE THREAD

**Issue by ChefkeGremmen** [BenjV/autosub#14]
Hi there,

I am running Auto-Sub on a ZFSGuru installation (so FreeBSD) and I get the following error 
"ERROR  scanDir: Skipping directory, file <filename>"
on each file which has characters like "é", "ó", "à" and the like.
My version info for auto-sub modules is;

Auto-Sub version: | 1.1.5
Python version: | 2.7.12 (default, Dec 20 2016, 02:07:35) [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)]
Python location: | /usr/local/bin
Requests library version: | 2.12.4
CherryPy version: | 8.7.0
Bootstrap version: | 3.3.6
jQuery version: | 1.9.1
jQuery DataTables version: | 1.10.12

**Comment by BenjV** [comment]
Most of the time this happens when the source of the files are from a windows origin and they are unpacked (either unpar or unrar) on a non windows machine.

The filenames are created with a windows codepage and unpacked on a filesysten (FreeBSD) that uses utf-8. Neither unrar nor unpar support translating from a codepage based system to a utf-8 system.
This is very logical because to be able tot do that you need to know the codepage that was used on the source system.

Only special character have this problem because standard ascii is equal on utf-8 and windows.

**Comment by ChefkeGremmen** [comment]
Ah, I see. Now that I have viewed the file through an SSH session the characters are replaced by '?'.

**Comment by BenjV** [comment]
They are not replaced but only shown as a ? because FreeBSD cannot interpret the bytecode.
