### ISSUE TITLE
Autosub crash

### ISSUE THREAD

**Issue by gillesoorts** [BenjV/autosub#30]
I've had a crash this afternoon with version 1.2.17 running on the latest Synology DSM. I had to manually restart Autosub from the Synology package center.

The log says:

12-01 13:29:23 ERR A7_Logout   :HTTPConnectionPool(host='www.addic7ed.com', port=80): Read timed out. (read timeout=22)
12-01 13:29:00 ERR getpage     :HTTPConnectionPool(host='www.addic7ed.com', port=80): Read timed out. (read timeout=13)
12-01 13:28:47 ERR getpage     :HTTPConnectionPool(host='www.addic7ed.com', port=80): Read timed out. (read timeout=13)

**Comment by MrMdemiC** [comment]
i also got that problem now for a couple of days, same issue and same log code

**Comment by BenjV** [comment]
The Addice7ed website has problems and is not online at the moment.

There is a small bug that causes autosub to crash during the logout when the login was successfull and autosub tries to logout when the website disapperas in between..
This will not happen if the website if offline when autosub tries to login.

The bug will be fixed in the next release of autosub.

**Comment by BenjV** [comment]
Fixed in 1.2.18
