### ISSUE TITLE
Tvdb API Error

### ISSUE THREAD

**Issue by skolto** [BenjV/autosub#39]
Hello,

ik keep getting an error from the Tvdb API.

Error from Tvdb API is: "Valid User Account Required"

i do have the Account Identifier, but where can i see my username ?

**Comment by BenjV** [comment]
You have to input your tvdb username and your tvdb account identifier which you got from tvdb when you created an account there.
So you did not input the correct information into the config page of autosub.

**Comment by skolto** [comment]
i tried the username, the one you login with and the site user id but both give an login error in the auto sub log files

**Comment by skolto** [comment]
Ok, its logged in now. but now i get the error Tvdb returnd an error: Resource not found

**Comment by BenjV** [comment]
Post the full filename of the show you were looking for on tvdb

**Comment by marcofranssen** [comment]
I had same issue, it appeared the tvdb renewed their webpage and therefore I had to reset my password to re-enable my account. After that it started working again. So for anyone else having this issue, you might just want to try to login on thetvdb.com to re-enable your account.

**Comment by BenjV** [comment]
That would be very strange.
The password has nothing to do with the API which autosub is using.
The account identifiers is used.

Besides that,  I did not have any problem with tvdb so I must assume that is was just some hikup in their system caused by the changing of their website,

And "resource not found" means that the show is not to be found and not "unable to login"

**Comment by marcofranssen** [comment]
Sorry for me it was 403. After logging in the api access started to work again.
