### ISSUE TITLE
path in config or -c option not working

### ISSUE THREAD

**Issue by Quiptix** [BenjV/autosub#45]
When starting AutoSub outside the directory where AutoSub.py is located it stops working.
It cannot find the templates and AutoSub.py gets deleted by itself.

When using -c option to specify the configuration, it seems to ignore it.

According to Github nothing has changed, what could have triggered this behaviour?
Update of Python/Cheetah? Cherrypy?

How to troubleshoot this? Logs doesn't provide any useful info.

Happy to communicate in dutch... ;-)

**Comment by BenjV** [comment]
It was always necessary to start autosub from the folder it is installed.

The -c option not working is a bug an will be fixed in the next release.
And logging is not possible, because it crashes before the logging is initialized.

In the next release it will no longer be necessary to start autosub from its own folder.

**Comment by Quiptix** [comment]
Oke! Then I don't have to investigate it any further!

Thanks
