### ISSUE TITLE
thetvdb api is not working anymore

### ISSUE THREAD

**Issue by marcofranssen** [BenjV/autosub#53]
It seems the tvdb api has upgraded to v3 and therefore the login doesn't work anymore.

Can we upgrade to this version which now requires an api token that can be created at https://thetvdb.com/dashboard/account/apikey

The v3 api also has some great documentation in the form of swagger.

https://api.thetvdb.com/swagger

**Comment by BenjV** [comment]
Tvdb V2 and V3 api are on the client side exactly the same the only thing they changed was the server side.
Because of this server side change all account identifiers were expired so everybody had to register again to get a new account identifier.

But a login is no longer needed for the information autosub needs from tvdb, I have removed the need for a login account.
So you can upgrade to the latest version of autosub and then you don't need to login on tvdb anymore.

**Comment by marcofranssen** [comment]
Awesome, that resolved all the errors. It works again 👍
